= Introducción

*¡Aventureros, atención! Vamos a jugar Hallasenderos* +
Imaginen que son parte de una película de fantasía medieval como _El Senor de los Anillos_ o _Calabozos y Dragones_ pero aquí *USTEDES* son los *Héroes*.

== ¿Qué es Hallasenderos?
Es un *Juego de mesa* donde se crean personajes únicos y viven aventuras épicas. Pero no es un juego de mesa normal, aquí el único límite es tu imaginación mientras que los dados (principalmente un #d20#) determinan lo que pasa.

== ¿Cómo se juega?
Vamos a adentrarnos más a detalle en el #próximo capítulo# pero a groso modo:

=== Creas un personaje
¿Quieres ser un bárbaro furioso?, ¿un hechizero que lanza bolas de fuego? o ¿un astuto ladrón?. ¡Todo es posible!

Hallasenderos tiene una amplia gama de razas y clases para creación de personajes por lo que puedes ser lo que sea que te imagines. Y lo que es mejor, si nada se parece a lo que tú quieres no hay problema *podemos crearlo*. Solo tienes que indicarle a tu #contramaestre# precisamente que es lo que deseas y lo haremos posible.
// de aquí pa abajo solo estan las ideas, falta detallar
¿Sientes ansiedad por tantas opciones? No pasa nada, tenemos #personajes prefabricados# los cuales son ideales para jugadores novatos o experimentados que quieres probar algo nuevo

=== Te adentras a un mundo de *Fantasía*
El contramaestre es el encargado de guiar a los jugadores por el mundo.....

=== Los dados marcan tu destino
Vas a atacar a alguien o pretendes convencer a un ogro de ir a  rescatar a la princesa del castillo mas alto de la torre mas lejana. Tira un dado de veinte lados (d20) y al resultado le sumas tus habilidades. ¡Entre más alto, mejor!

== ¿Por qué probar?

Es cooperativo: todos nos divertimos juntos tabajando en equipo.

No hay presiones, si empiezan a divagar, distraerse y perderse, ¡es parte de la diversión!

Aprender sobre la marcha, que la cantidad de información no te abruma, solo necesitan ganas de pasarla bien
