#+TITLE: Hallasenderos
#+DESCRIPTION: Guía para el jugador
#+auto_tangle: t
#+STARTUP: showeverything

Esta es la guía del jugador, esta escrita en AsciiDoc para hacer uso de la herramienta [[https://docs.antora.org/antora/latest/][antora]] para pubicarlo en pf2e.ale.lat y por otro lado para usar AsciiDoctor y publicarlo como libro usando la misma raíz, de momento lo único que me falta es ser bueno en adoc y hacer que emacs sea capaz de reconocer la escritura

Para hacer uso de esta herramienta se ocupa un archivo en raíz que hay que ir mejorando porque aún no entiendo del todo bien de que va esto
#+begin_src yml :tangle "antora.yml"
name: core
title: Player Core
version: latest
display_version: default
asciidoc:
    attributes:
        source-language: asciidoc@
        xrefstyle: short@
nav:
    - modules/ROOT/nav.adoc
    - modules/gp/nav.adoc
    - modules/char/nav.adoc
#+end_src

* ROOT
Los nav.adoc son los que le indican a antora la organización del índice, normalmente irían solo con * al principio pero el problema es que como finalmente éste es un archivo ORG, se interpreta como headers y rompe todo el orden, al poner una , antes ,* a la hora de producir el archivo lo escapa, similar a como \ funciona en shell.
#+begin_src adoc :tangle "modules/ROOT/nav.adoc" :mkdirp yes
,* xref:index.adoc[]

[]
,* RPG
,** xref:gameMaster.adoc[]
,** xref:attributes.adoc[]
,** xref:armorClass.adoc[]
#+end_src
Aquí inicia con una leve introducción a lo que es un juego de rol y los objetivos del juego
** Introducción
#+BEGIN_SRC adoc :tangle "modules/ROOT/pages/index.adoc" :mkdirp yes
= Introducción

*¡Aventureros, atención! Vamos a jugar Hallasenderos* +
Imaginen que son parte de una película de fantasía medieval como _El Senor de los Anillos_ o _Calabozos y Dragones_ pero aquí *USTEDES* son los *Héroes*.

== ¿Qué es Hallasenderos?
Es un *Juego de mesa* donde se crean personajes únicos y viven aventuras épicas. Pero no es un juego de mesa normal, aquí el único límite es tu imaginación mientras que los dados (principalmente un #d20#) determinan lo que pasa.

== ¿Cómo se juega?
Vamos a adentrarnos más a detalle en el #próximo capítulo# pero a groso modo:

=== Creas un personaje
¿Quieres ser un bárbaro furioso?, ¿un hechizero que lanza bolas de fuego? o ¿un astuto ladrón?. ¡Todo es posible!

Hallasenderos tiene una amplia gama de razas y clases para creación de personajes por lo que puedes ser lo que sea que te imagines. Y lo que es mejor, si nada se parece a lo que tú quieres no hay problema *podemos crearlo*. Solo tienes que indicarle a tu #contramaestre# precisamente que es lo que deseas y lo haremos posible.
// de aquí pa abajo solo estan las ideas, falta detallar
¿Sientes ansiedad por tantas opciones? No pasa nada, tenemos #personajes prefabricados# los cuales son ideales para jugadores novatos o experimentados que quieres probar algo nuevo

=== Te adentras a un mundo de *Fantasía*
El contramaestre es el encargado de guiar a los jugadores por el mundo.....

=== Los dados marcan tu destino
Vas a atacar a alguien o pretendes convencer a un ogro de ir a  rescatar a la princesa del castillo mas alto de la torre mas lejana. Tira un dado de veinte lados (d20) y al resultado le sumas tus habilidades. ¡Entre más alto, mejor!

== ¿Por qué probar?

Es cooperativo: todos nos divertimos juntos tabajando en equipo.

No hay presiones, si empiezan a divagar, distraerse y perderse, ¡es parte de la diversión!

Aprender sobre la marcha, que la cantidad de información no te abruma, solo necesitan ganas de pasarla bien
#+END_SRC

queda ver como será posible linkear a otros capítulos, de momento estan marcados entre #así# pero pues no sé si sea más viable más adelante
** Contramaestre
#+begin_src adoc :tangle "modules/ROOT/pages/gameMaster.adoc" :mkdirp yes
= Contramaestre

Gamemaster (GM) -> Maestro del Juego, [.underline]#Contramaestre#, Director del juego, etc.

== ¿Qué es un contramaestre?
En todo juego de rol se necesita un voluntario que es quien se encargaga de contar la historia y mantener control de los personajes extra del mundo tanto monstruos como pueblerinos y nobeza todo lo controla el contramaestre. Hay reglas especificas que debe respetar pero de momento no vamos a preocuparnos por nada de eso porque aquí solo vamos a centrarnos del lado opuesto que son personajes jugables
#+end_src
** Atributos
#+begin_src adoc :tangle "modules/ROOT/pages/attributes.adoc" :mkdirp yes
= Atributos: Attribute
Toda criatura tiene seis atributos que lo caracterizan, estos son:

 *F* uerza _Strength_
 *D* estreza _Dexterity_
 *R* esistencia _Constitution_
 *I* nteligencia _Intelligence_
 *S* abiduría _Wisdom_
 *C* arísma _Charisma_

[note]
En la versión _remasterizada_ de Pathfinder se desecharón los valores del 1 al 20 en los atributos, dejando únicamente los modificadores; siendo *0* el valor por defecto y de ahí partiendo a +1, +2, -1, etc.
#+end_src
** Armor Class
#+begin_src adoc :tangle "modules/ROOT/pages/armorClass.adoc" :mkdirp yes
= Nivel de armadura: Armor Class (AC)

Toda criatura en el juego tiene un valor de nivel de armadura. Éste valor determina que tan difícil es atacar a la criatura. Básicamente es el DC de la criatura en contra del ataque.
#+end_src
* Gameplay
A ver que tal sale
#+begin_src adoc :tangle "modules/gp/nav.adoc" :mkdirp yes
,* Gaming
,** xref:actions.adoc[]
,*** xref:basicActions.adoc[]
,**** xref:attack.adoc[]
#+end_src

== statblock
[options='header,footer',frame='none',grid='rows',width='85%',role='center']
|===
3+|Nombre ◆ >|Nivel
4+a|[small underline red-background]#*+Rasgos+*#
>.^a|[small]#*Requisitos*# 3+a|[small]#+Un mínimo de atributos, dotes, competencia, etc. que se deben cumplir para poder emplear esta habilidad. El nivel mencionado de igual manera es un requisito.+#
>.^a|[small]#*Frecuencia*# 3+a|[small]#+Límite de cada cuando se puede usar la habilidad.+#
>.^a|[small]#*Desencadenante*# 3+a|[small]#+Las reacciónes y algunas acciones libres tienen desencadenantes que se deben cumplir para poder ser empleadas.+#
>.^a|[small]#*Ocupa*# 3+a|[small]#+A veces debes poseer ciertos accesorios o estaren alguna circunstancia específica para poder emplear la habilidad.+#
4+|Aquí se describen los efectos, beneficios o las reglas. Si la regla es una acción, se explica cuál es su efecto o cuánto debes rolar. Si es un dote que modifica una acción existente o brinda un efecto persistente, los beneficios se explican aquí.
4+|**Especial** Cualquier cualidad especial de la regla se explica en esta sección. Normalmente ésta sección aparece en dotes que puedes elegir más de una, explicando lo que sucede si lo haces.
A veces una habilidad brindará múltiples acciones o una acción adicional a otros beneficios. Están condensadas en un formato corto usando las mísmas categorías. +
**Nombre de la acción ◆** (Rasgos) **Frecuencia** que tan seguido se puede usar; **Desencadenante** cuando se puede emplear la reacción o acción libre; **Ocupa** algunas acciones necesitan circunstancias específicas enlistadas aquí; **Efecto** explica cómo la habilidad cambia al mundo.
^a|[big]#✅# +
[small green-background]#*Efectos cuando el rolado es un éxito crítico*#
^a|[big]#🟩# +
[small green]#Efectos cuando el rolado es un éxito#
^a|[big]#🟥# +
[small red]#Efectos cuando el rolado es un fallo#
^a|[big]#🆑# +
[small red-background]#*Efectos cuando el rolado es un fallo crítico*#
|===

** Acciones
#+begin_src adoc :tangle "modules/gp/pages/actions.adoc" :mkdirp yes
= Acciones

== Acción
Dinámica que puede llevar a cabo cualquier personaje durante su turno en un encuentro; o fuera de estos, en cualquier momento a criterio del #contramaestre#. En los encuentros, al inicio de su turno cada criatura obtiene *TRES* acciones más *UNA* reacción, no acumulables. Hay cuatro tipos de acciones:

Acción sencilla:: Se completa en un tiempo muy corto. Son auto-contenidas, y sus efectos se manifiestan en el lapso de una sola acción.
Actividad:: Normalmente toman más tiempo y requieren de múltiples acciones, las cuales se consumen sucesivamente y durante el mismo turno.
Reacción:: Taiene <<Desencadenante, desencadenantes>>, los cuales deben cumplirse en orden de poder usar la reacción, ya sea tu turno o no. Fuera de encuentros, el uso de reacciones es más flexible y bajo el criterio del #contramaestre#.
Acción libre:: Sin costo alguno que pueden tener, o no, <<Desencadenante, desencadenantes>>, en caso de no tener desencadenante la acción libre debe hacerse en tu turno y no puede ser empleada simultáneamente junto otra acción.

[NOTE]
.Simbología
====
◆   Acción sencilla +
◆◆  Actividad de doble acción +
◆◆◆ Actividad de triple acción +
⤾   Reacción +
◇   Acción libre
====

== Actividad
Fuera de encuentros, las actividades pueden tomar minutos, horas o hasta incluso días. Éste tipo de actividades vienen indicadas con el #rasgo# pertinente para indicar que se les planea usar en esos modos. Por lo general puedes hacer otras cosas mientras mientras se lleva a cabo la actividad, siempre y cuando tenga sentido. Por ejemplo, si estas Reparando un accesorio puedes tomarte un descanso e ir a platicar a una taberna, pero no podrías Descifrar un códice al mismo tiempo.

== Desencadenante
Se pueden usar acciones con desencadenantes solo en respuesta a ciertos eventos los cuales vienen detallados en la descripción de estas. Cuando el desencadenante se cumple, y solo hasta que este se cumple, puedes elegir, o no, llevar a cabo la respuesta.

=== Limitaciones
Los desencadenantes listados en la descripción de una acción limitan cuándo puedes usar estos. Pero solo puedes usar *UNA* acción en respuesta a un determinado desencadenante. Por ejemplo, si tuvieras dos reacciones que como desencadenante menciona al inicio de tu turno puedes usar cualquiera de ellas, pero no ambas. Esta limitación esta basada en una por criatura no por desencadenante, es decir, múltiples criaturas pueden reaccionar a un mismo desencadenante.
#+end_src
*** Acciones básicas
#+begin_src adoc :tangle "modules/gp/pages/basicActions.adoc" :mkdirp yes
= Acciones básicas

Representan obras comunes que cualquier criatura es capaz de realizar.
#+end_src
**** Agarrarse
#+begin_src adoc :tangle "modules/gp/pages/grabAnEdge.adoc" :mkdirp yes
[options='header,footer',frame='none',grid='rows',width='85%',role='center']
|===
3+|Agarrarse ⤾ >|
4+a|[small underline red-background]#*+Manipular 🤌+*#
>.^a|[small]#*Desencadenante ⛓*# 3+a|[small]#+Caes de un borde o pasas a lado de uno mientras caes.+#
>.^a|[small]#*Requisitos 🔏*# 3+a|[small]#+No tienes las manos atadas ni estás neutralizado de alguna otra forma.+#

4+a|Cuando caes de un borde o bien pasas a lado de uno mientras caes, puedes intentar [underline]#*Agarrarte*# para potencialmente detener tu caída. Debes tener éxito en un rolado de _Reflejos_. Si te agarras del borde, puedes después _Trepar_ utilizando _Atletismo_
^a|[big]#✅# +
[small green-background]#*Te agarras del borde, tengas o no una mano libre. Sigues sufriendo daño debido a la distancia caída hasta ese momento, pero tratas la caída como si fuera 6m menor.*#
^a|[big]#🟩# +
[small green]#Si tienes por lo menos una mano libre, te agarras del borde deteniendo tu caída. Si no tienes ninguna mano libre, continúas cayendo como si hubieras fallado.#
^a|[big]#🟥# +
[small red]#Sigues cayendo.#
^a|[big]#🆑# +
[small red-background]#*Te lastimas al tratar de agarrarte. Además del daño total por la distancia caída, le sumas 1d6 de daño _Contundente_*#
|===
#+end_src
**** Alzar escudo
#+begin_src adoc :tangle "modules/gp/pages/raiseAShield.adoc" :mkdirp yes
[options='header',frame='none',grid='rows',width='85%',role='center']
|===
3+|Alzar escudo ◆ >|
4+a|[small underline red-background]#*+Manipular 🤌+*#
>.^a|[small]#*Requisitos 🔏*# 3+a|[small]#+Empuñar un escudo.+#

4+a|Antepones el escudo para que te proteja. Obtienes la bonificación para tu #protección# que se indica en la descripción del escudo. Tu escudo permanece alzado hasta el inicio de tu siguiente turno, por lo que la bonificación es persistente pero tus reacciones serán más limitadas.
|===
#+end_src
**** Apoyar
#+begin_src adoc :tangle "modules/gp/pages/aid.adoc" :mkdirp yes
[options='header,footer',frame='none',grid='rows',width='85%',role='center']
|===
3+|Apoyar ⤾ >|
>.^a|[small]#*Desencadenante ⛓*# 3+a|[small]#+Un aliado esta a punto de realizar una acción que requiera un rolado.+#
>.^a|[small]#*Requisitos 🔏*# 3+a|[small]#+El aliado esta dispuesto a aceptar tu ayuda y tú te has perparado para apoyarlo.+#

4+a|Tratas de ayudar a tu aliado en su hacer. Para poder usar ésta reacción, primero debes estar preparado para apoyar, normalmente usando la acción _Preparar_ durante tu turno, donde debes explicarle al #contramaestre# exactamente cómo es que pretendes ayudar, él determinará si dicho apoyo es viable y a su vez la #dificultad# del rolado.
^a|[big]#✅# +
[small green-background]#*Le proporcionas a tu aliado un bono de _+2_ a su rolado, si eres maestro en la habilidad que checa tu aliado _+3_ y si eres legendario _+4_.*#
^a|[big]#🟩# +
[small green]#Le proporcionas a tu aliado un bono de _+1_ a su rolado.#
^a|[big]#🟥# +
[small red]#Tu aliado ignora tu apoyo.#
^a|[big]#🆑# +
[small red-background]#*Tu aliado sufre una penalidad de _-1_ en su rolado.*#
|===
#+end_src
**** Arrastrarse
#+begin_src adoc :tangle "modules/gp/pages/crawl.adoc" :mkdirp yes
[options='header',frame='none',grid='rows',width='85%',role='center']
|===
3+|Arrastrarse ◆ >|
4+a|[small underline red-background]#*+Movimiento 🏃+*#
>.^a|[small]#*Requisitos 🔏*# 3+a|[small]#+Debes estar _desplomado_ y tener una velocidad de al menos 2m.+#

4+a|Te mueves arrastrandote contra el suelo hasta máximo 1 metro de distancia y sigues _desplomado_.
|===
#+end_src
**** Atacar
#+begin_src adoc :tangle "modules/gp/pages/attack.adoc" :mkdirp yes
[options='header,footer',frame='none',grid='rows',width='85%',role='center']
|===
3+|Atacar ◆ >|
4+a|[small underline red-background]#*+Ataque ⚔️+*#

4+a|Atacas con un arma que empuñas o desarmado, apuntando a una criatura a tu alcance (para un ataque cuerpo a cuerpo) o dentro de tu rango (para un ataque a distancia). Haz un rolado correspondiente al ataque que estas utilizando, y compáralo con la #protección# de la criatura objetivo para determinar el resultado. Si ya has realizado cualquier acción con el rasgo _Ataque_ en tu mismo turno, sufres la penalidad por ataques consecutivos correspondiente.
^a|[big]#✅# +
[small green-background]#*Infliges el doble de daño.*#
^a|[big]#🟩# +
[small green]#Infliges el daño correspondiente al arma utilizada.#
^a|[big]#🟥# +
[small red]#Nada.#
^a|[big]#🆑# +
[small red-background]#*Recibes 1d4 de daño por algún accidente debido a tu torpeza.*#
|===
#+end_src
**** Buscar
#+begin_src adoc :tangle "modules/gp/pages/seek.adoc" :mkdirp yes
[options='header,footer',frame='none',grid='rows',width='85%',role='center']
|===
3+|Buscar ◆ >|
4+a|[small underline red-background]#*+Concentración ⚠️️+*#

4+a|Puedes examinar un área en busqueda de signos de criaturas u objetos. Podrías sufrir un penalizador si eligieras un área muy grande o que estuviera lejos. El #contramaestre# puede determinar si necesitas _Buscar_ como una actividad, lo que requiere más acciones o incluso minutos u horas si buscas en una zona particularmente atestada. Si buscas criaturas, haz un rolado de persepción y el #contramaestre# comparará el resultado con el _Sigilo_ de cualquier criatura no detectada o escondida en la zona; de igual manera la #dificultad# para detectar objetos. Una criatura a la que detectas podría permanecer escondida, en lugar de volverse observada si estás utilizando un sentido impreciso o si algún efecto (como por ejemplo la invisibilidad) evita que el sujeto sea observado.
2+^a|[big]#✅# +
[small green-background]#*Si estás buscando criaturas, cualquier criatura no detectada o escondida pasa a ser observada por ti. Si estabas buscando un objeto, averiguas su ubicación.*#
2+^a|[big]#🟩# +
[small green]#Si estabas buscando criaturas, cualquier criatura no detectada pasa a estar escondida de ti en lugar de no detectada, y cualquier criatura escondida pasa a ser observada por ti. Si estabas buscando un objeto obtienes una clara pista sobre su paradero.#
|===

#+end_src
**** Cautelar
#+begin_src adoc :tangle "modules/gp/pages/step.adoc" :mkdirp yes
[options='header',frame='none',grid='rows',width='85%',role='center']
|===
3+|Cautelar ◆ >|
4+a|[small underline red-background]#*+Movimiento 🏃+*#
>.^a|[small]#*Requisitos 🔏*# 3+a|[small]#+Tener una velocidad de al menos 2m.+#

4+a|Te mueves cuidadosamente máximo 1m. A diferencia de otros tipos de movimiento, dar un paso con cautela no desencadena reacciones, como por ejemplo ataques oportunos que son desencadenados por acciones de movimiento. Tambien proporciona una bonificación por situación al sufrir la activación de trampas. No puedes dar un paso cauteloso en terreno difícil.
|===
#+end_src
**** Cubrirse
#+begin_src adoc :tangle "modules/gp/pages/takeCover.adoc" :mkdirp yes
[options='header',frame='none',grid='rows',width='85%',role='center']
|===
3+|Cubrirse ◆ >|
>.^a|[small]#*Requisitos 🔏*# 3+a|[small]#+Te estas beneficiando de cobertura, posees un rasgo que te permita ponerte a cubierto o estás _desplomado_+#

4+a|Te arrimas a una pared o te agachas tras un obstáculo para sacar partido de la _cobertura_. Si tendrías cobertura normal, en su lugar obtienes cobertura mayor, que proporciona un bonificador +4 por circunstancia a tu #protección#, a los rolados de salvación de _Reflejos_ contra efectos de área y a las pruebas de _Sigilo_ para evitar tu detección. Si tendrías cobertura menor, en su lugar obtienes los beneficios de una cobertura normal, es decir un bonificador de +2 por circunstancia. Esto dura hasta que te mueves de tu espacio actual, usas alguna acción de ataque, quedas inconciente o voluntariamente acabas con este efecto como acción libre.
|===
#+end_src
**** Desviar la mirada
#+begin_src adoc :tancle "modules/gp/pages/avertGaze.adoc" :mkdirp yes
[options='header',frame='none',grid='rows',width='85%',role='center']
|===
3+|Desviar la mirada ◆ >|

4+a|Desvias la mirada del peligro. Obtienes un bonificador +2 por circunstancia a los rolados de salvación contra acciones que tengan rasgo visual. Sin embargo, al mismo tiempo pierdes de vista el objetivo por lo que tienes una penalidad de -1 en todos los ataques contra éste y en tu protección ante dicho objetivo. Tu mirada permanece desviada hasta el inicio de tu próximo turno.
|===

#+end_src
* Personaje
#+begin_src adoc :tangle "modules/char/nav.adoc" :mkdirp yes
,* xref:character.adoc[]
,** xref:ancestries.adoc[]
,** xref:classes.adoc []
,** xref:backdrounds.adoc[]
#+end_src
** Personaje
#+begin_src adoc :tangle "modules/char/pages/character.adoc" :mkdirp yes
= Personaje: Character

== Héroe: Player Character (PC)
Éste es un personaje creado y controlado por el jugador.

== Personaje no jugable: Nonplayer CHaracter (NPC)
#+end_src
*** Ascendencia
#+begin_src adoc :tangle "modules/char/pages/ancestry.adoc" :mkdirp yes
= Ascendencia: Ancestry _porque decir *raza* es racista_

La ascendencia es el tipo de gente al que pertenece el personaje o la criatura. La ascendencia determina los valores iniciales de **golpes de vida**[HP], idiomas, sentidos y velocidad; además brinda ciertas características[feats] asociadas exclusivamente a su ascendencia.
#+end_src
*** Clase
#+begin_src adoc :tangle "modules/char/pages/class.adoc" :mkdirp yes
= Clase: Class

La clase representa la especialidad del aventurero. Esta determina la mayoría de las
#+end_src
*** Bagaje
#+begin_src adoc :tangle "modules/char/pages/background.adoc" :mkdirp yes
= Bagaje: Background

El bagaje representa las experiencias que ha vivído el personaje previamente, este le proporciona una característica y entrenamiento en una o más habilidades.
#+end_src
